[project]
name = "kadigrec"
version = "0.1.0"
authors = [
    {name="Gabriele Beltramo", email="hello@gbeltramo.com"},
]
description = "Code for the Kaggle Digit Recognizer competition."
readme = "README.org"
requires-python = ">=3.10,<3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[build-system]
requires = ["setuptools>=67.0.0"]
build-backend = "setuptools.build_meta"
