name: ka-pytorch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.12.0
  - alsa-lib=1.2.8
  - antlr-python-runtime=4.9.3
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - astor=0.8.1
  - asttokens=2.4.0
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attr=2.5.1
  - attrs=23.1.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bcrypt=4.0.1
  - beautifulsoup4=4.12.2
  - black=23.9.1
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.0.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - build=0.7.0
  - bumpver=2023.1126
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.4
  - conda-pack=0.7.1
  - configparser=5.3.0
  - contourpy=1.1.1
  - cryptography=41.0.4
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - databricks-cli=0.17.7
  - dbus=1.13.6
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docker-py=6.1.3
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.12.4
  - flask=2.3.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.36
  - glib=2.78.0
  - glib-tools=2.78.0
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - graphite2=1.3.13
  - graphviz=7.1.0
  - greenlet=2.0.2
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - gtk2=2.24.33
  - gts=0.7.6
  - gunicorn=21.2.0
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - iniconfig=2.0.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - isoduration=20.11.0
  - itsdangerous=2.1.2
  - jack=1.9.22
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - kaggle=1.5.16
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - lexid=2021.1006
  - lib3to6=202107.1047
  - libabseil=20230125.3
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.2.10
  - libcups=2.3.3
  - libcurand=10.3.3.141
  - libcurl=8.1.2
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.1
  - libgd=2.3.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.47
  - libgrpc=1.56.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libnvjpeg=11.8.0.2
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=4.23.3
  - librsvg=2.54.4
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - llvmlite=0.40.1
  - looseversion=1.3.0
  - lz4-c=1.9.4
  - mako=1.2.4
  - markdown=3.4.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mlflow=2.7.1
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpg123=1.31.3
  - mpmath=1.3.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.6
  - networkx=3.1
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.92
  - numba=0.57.1
  - numpy=1.24.4
  - oauthlib=3.2.2
  - omegaconf=2.3.0
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl
  - orc=1.9.0
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - pango=1.50.14
  - paramiko=3.3.1
  - parso=0.8.3
  - pathlib2=2.3.7.post1
  - pathspec=0.11.2
  - pcre2=10.40
  - pep517=0.13.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - pluggy=1.3.0
  - ply=3.11
  - polars=0.19.3
  - prometheus_client=0.17.1
  - prometheus_flask_exporter=0.22.4
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=4.23.3
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - pyarrow=12.0.1
  - pycparser=2.21
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pynacl=1.5.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytest=7.4.2
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-slugify=8.0.1
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - querystring_parser=1.2.4
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.3
  - s2n=1.3.46
  - scikit-learn=1.3.1
  - scipy=1.11.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.11
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.21
  - sqlparse=0.4.4
  - stack_data=0.6.2
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.9.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchdata
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.10.0
  - typing=3.10.0.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucx=1.14.1
  - uri-template=1.3.0
  - urllib3=2.0.4
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.3
  - werkzeug=2.3.7
  - wheel=0.41.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
